# Setup
# Specify the author for blog posts
author:
  name: bijumon
  url: https://bijumon.github.io/about/
  email: me@gee.mail

title: Firehose Weekly
tagline: fuel for the dev firehose
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: ""
url: "https://bijumon.github.io"
permalink: "/:categories/:slug/"

plugins:
  - jekyll-feed

markdown: CommonMark
commonmark:
  options: ["FOOTNOTES"]
  extensions: ["strikethrough", "autolink", "table"]

exclude:
    - Readme.md
    - Gemfile
    - Gemfile.lock

# frontmatter defaults
defaults:
  -
    scope:
      path: ""
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"